### ISSUE TITLE
`spread` is not defined on line 159 of mcmc.py

### ISSUE THREAD

**Issue by warrickball** [grd349/PBjam#149]
Hi,

This script 
````python
import pbjam as pb
import lightkurve as lk

def do_one(l):
    return l.PDCSAP_FLUX.remove_nans().flatten().normalize().remove_outliers()

lcs = lk.search_lightcurvefile(3662838, cadence='short').download_all()
lc = do_one(lcs[0]).append([do_one(lc) for lc in lcs[1:]])
pg = lc.to_periodogram(normalization='psd', minimum_frequency=500., maximum_frequency=1500.)
numax, dnu, teff, bp_rp = [1095., 50.], [78.51, 1.51], [6967., 100.], [0.5955, 0.0020]
star = pb.star(3662838, pg, numax, dnu, teff, bp_rp, make_plots=True)
star(norders=5)
````

just crashed with the error message

````
/home/wball/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Traceback (most recent call last):
  File "PBjam_bug_1.py", line 16, in <module>
    star(norders=5)                                                                                                                                                                                           
  File "/home/wball/pypi/PBjam/pbjam/star.py", line 146, in __call__
    self.run_epsilon(bw_fac=bw_fac)
  File "/home/wball/pypi/PBjam/pbjam/star.py", line 104, in run_epsilon
    bp_rp=self.bp_rp)
  File "/home/wball/pypi/PBjam/pbjam/guess_epsilon.py", line 288, in __call__
    self.samples = self.kde_sampler()
  File "/home/wball/pypi/PBjam/pbjam/guess_epsilon.py", line 162, in kde_sampler
    return self.fit()
  File "/home/wball/pypi/PBjam/pbjam/mcmc.py", line 109, in __call__
    pos = self.fold(pos, spread)
  File "/home/wball/pypi/PBjam/pbjam/mcmc.py", line 159, in fold
    good_mad = st.median_absolute_deviation(flatchains, axis = 0) * spread
NameError: name 'spread' is not defined
````

It's quite clear that `spread` isn't defined but I'm not sure whether the intention was to delete it or make it a keyword argument.

**Comment by grd349** [comment]
Thanks @warrickball - Excellent point.  I think the correct behaviour should be a keyword - spread=0.1 -  would probably be about right.

**Comment by grd349** [comment]
The above example is not working well - the star is too far from the red giant dominated prior for now.

Need to add a warning based on a comparison of the input star and what is in the prior data.  This should probably be a new issue in it's own right.

**Comment by grd349** [comment]
@nielsenmb Does this warrant an update on PyPi?

**Comment by warrickball** [comment]
I've only installed my fork and am not smart enough to use modern sorcery like "virtual environments" but a quick glance in the tarball on PyPI suggests that yes, the PyPI version contains this bug.

**Comment by nielsenmb** [comment]
Going to close this issue. It appears to have been fixed for a while now.
